name: chocolatine

on: [push, pull_request]
##branches

env:
    MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-STG-2-1-chocolatine-mohamed.mazouz.git"
    EXECUTABLES: "mysh"

jobs:
    check_coding_style:
        name: check coding style
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/epitech/coding-style-checker:latest
        outputs:
            my_output: ${{ steps.check_coding_style.outputs.style_errors }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: get coding-style errors
              id: check_coding_style
              run: |
                check.sh $(pwd) $(pwd)
                while read line; do
                  echo "::set-output name=style_errors::$line"
                done < coding-style-reports.log
            
            - name: display-errors
              if: ${{ steps.check_coding_style.outputs.style_errors != '' }}
              run: |
                echo "coding style errors:"
                echo "${{ steps.check_coding_style.outputs.style_errors }}"
            
                
        
        
