name: chocolatine

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

env:
    MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-STG-2-1-chocolatine-mohamed.mazouz.git"
    EXECUTABLES: "mysh"

jobs:
    check_coding_style:
        name: check coding style
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/epitech/coding-style-checker:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: get coding-style errors
              id: check_coding_style
              run: |
                check.sh $(pwd) $(pwd)
                while read ERROR; do
                  filename=$(echo $ERROR | cut -d ':' -f 1 | cut -d '/' -f 2)
                  line=$(echo $ERROR | cut -d ':' -f 2)
                  gravity=$(echo $ERROR | awk -F ':' '{print $3}')
                  error=$(echo $ERROR | awk -F ':' '{print $2}' | awk '{print $1}')
                  echo "Filename: $filename"
                  echo "Line: $line"
                  echo "Error: $error"
                  echo "Gravity: $gravity"
                  echo "::error file=$filename,line=$line,title=$gravity coding style error::$error"
                done < coding-style-reports.log
                
        
        
