name: chocolatine

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

env:
    MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-STG-2-1-chocolatine-mohamed.mazouz.git"
    EXECUTABLES: "mysh"

jobs:
    check_coding_style:
        name: check coding style
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/epitech/coding-style-checker:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: get coding-style errors
              id: check_coding_style
              run: |
                check.sh $(pwd) $(pwd)
                echo "lol"
                while read error; do
                  echo $error
                done < coding-style-reports.log
                
        
        
